# Generated by Django 6.0 on 2025-12-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('SHIPPING', 'Shipping')], max_length=10),
        ),
    ]
